### ISSUE TITLE
Position contribute

### ISSUE THREAD

**Issue by FilippoComastri** [wogur110/PNI_Anomaly_Detection#1]
Hi. When you compute histograms relative to position information ( p(c|Cdist)), why you use embedding coreset (Cemb) instead of distribution coreset (Cdist) , as explained in the paper? As I see you used Cdist only for neighourhood contribute but not for position.
I'm interested to know if there's a specific reason for this choice.

**Comment by wogur110** [comment]
Hi. distribution coreset (Cdist) is subset of embedding coreset (Cemb). (|Cdist| < |Cemb|) I use embedding coreset (Cemb) to compute histogram because it can output more accurate normal feature distribution (p(c|Cemb). On the other hand, I use dsitribution coreset (Cdist) to compute neighborhood contribute due to limited size of MLP.
